version: '3.8'

services:
  db-skin:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: fpf2025
    ports:
      - "5433:5432"
    networks:
      - app-network

  web:
    build: .
    image: api-skin
    ports:
      - "8000:8000"
    environment:
      DB_ENGINE: django.db.backends.postgresql_psycopg2
      DB_HOST: db-skin
      DB_PORT: 5432
      DB_NAME: skin
      DB_USER: postgres
      DB_PASSWORD: fpf2025
    depends_on:
      - db-skin
    networks:
      - app-network

  pgadmin-api-core:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "user@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "14549:80"
    networks:
      - app-network

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9002:9001"  # Modifique de 9001 para 9002
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin
    command: server /data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
