# Generated by Django 5.2.1 on 2025-05-18 19:30

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='dt_created')),
                ('date_modified', models.DateTimeField(auto_now=True, db_column='dt_modified')),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('name', models.CharField(db_column='tx_name', max_length=255)),
                ('date_of_birth', models.DateField(db_column='dt_date_of_birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], db_column='tx_gender', max_length=10)),
                ('cpf', models.CharField(db_column='tx_national_id', max_length=14, unique=True)),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('professional_id', models.CharField(db_column='tx_professional_id', max_length=255, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='dt_created')),
                ('date_modified', models.DateTimeField(auto_now=True, db_column='dt_modified')),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('date_consultation', models.DateTimeField(db_column='dt_date_consultation')),
                ('notes', models.TextField(blank=True, db_column='tx_notes', null=True)),
                ('agent', models.ForeignKey(db_column='id_agent', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(db_column='id_patient', on_delete=django.db.models.deletion.DO_NOTHING, to='core.patient')),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FileImageSkin',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='dt_created')),
                ('date_modified', models.DateTimeField(auto_now=True, db_column='dt_modified')),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('filename', models.CharField(db_column='tx_file_name', max_length=255)),
                ('remote_name', models.CharField(db_column='tx_remote_name', max_length=1024)),
                ('consultation', models.ForeignKey(db_column='id_consultation', on_delete=django.db.models.deletion.DO_NOTHING, to='core.consultation')),
            ],
            options={
                'db_table': 'file_image_item',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='dt_created')),
                ('date_modified', models.DateTimeField(auto_now=True, db_column='dt_modified')),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('result', models.CharField(db_column='tx_result', max_length=255)),
                ('confidence', models.FloatField()),
                ('model_version', models.CharField(db_column='tx_model_version', default='v1', max_length=20)),
                ('image', models.ForeignKey(db_column='id_image', on_delete=django.db.models.deletion.DO_NOTHING, to='core.fileimageskin')),
            ],
            options={
                'db_table': 'analysis_result',
                'managed': True,
            },
        ),
    ]
