# Generated by Django 5.2.1 on 2025-05-30 23:33

import core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysisresult',
            options={'managed': True, 'verbose_name': 'Resultado de Análise', 'verbose_name_plural': 'Resultados de Análise'},
        ),
        migrations.AlterModelOptions(
            name='consultation',
            options={'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultas'},
        ),
        migrations.AlterModelOptions(
            name='fileimageskin',
            options={'managed': True, 'verbose_name': 'Imagem de Pele', 'verbose_name_plural': 'Imagens de Pele'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='user_created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_analysis_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultation',
            name='photo_location',
            field=models.CharField(blank=True, db_column='tx_photo_location', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='user_created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_consultations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fileimageskin',
            name='image_file',
            field=models.ImageField(blank=True, db_column='im_image_file', null=True, upload_to='analysis_images/'),
        ),
        migrations.AddField(
            model_name='fileimageskin',
            name='user_created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='cellphone',
            field=models.CharField(blank=True, db_column='nb_cellphone', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, db_column='tx_email', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='user_created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='image',
            field=models.ForeignKey(db_column='id_image', on_delete=django.db.models.deletion.DO_NOTHING, related_name='analysis_results', to='core.fileimageskin'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='agent',
            field=models.ForeignKey(db_column='id_agent', on_delete=django.db.models.deletion.DO_NOTHING, related_name='consultations_as_agent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='date_consultation',
            field=models.DateTimeField(db_column='dt_date_consultation', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(db_column='id_patient', on_delete=django.db.models.deletion.DO_NOTHING, related_name='consultations', to='core.patient'),
        ),
        migrations.AlterField(
            model_name='fileimageskin',
            name='consultation',
            field=models.ForeignKey(db_column='id_consultation', on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='core.consultation'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='cpf',
            field=models.CharField(blank=True, db_column='tx_national_id', max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, db_column='dt_date_of_birth', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], db_column='tx_gender', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_column='tx_username', error_messages={'unique': 'Já existe um usuário com este nome de usuário.'}, help_text='Obrigatório. 150 caracteres ou menos. Letras, números, @/./+/-/_ e espaços.', max_length=150, unique=True, validators=[core.validators.custom_username_validator]),
        ),
    ]
