# Generated by Django 5.2.1 on 2025-05-23 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='cellphone',
            field=models.IntegerField(db_column='nb_cellphone', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(db_column='tx_email', max_length=254, null=True),
        ),
    ]
