# Generated by Django 5.2.1 on 2025-06-01 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(db_column='id_patient', on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='core.patient'),
        ),
    ]
