# Generated by Django 5.2.1 on 2025-06-03 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_consultation_patient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysisresult',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='consultation',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='fileimageskin',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='analysisresult',
            name='user_created_by',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='photo_location',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='user_created_by',
        ),
        migrations.RemoveField(
            model_name='fileimageskin',
            name='image_file',
        ),
        migrations.RemoveField(
            model_name='fileimageskin',
            name='user_created_by',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user_created_by',
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='image',
            field=models.ForeignKey(db_column='id_image', on_delete=django.db.models.deletion.DO_NOTHING, to='core.fileimageskin'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='agent',
            field=models.ForeignKey(db_column='id_agent', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='date_consultation',
            field=models.DateTimeField(db_column='dt_date_consultation'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(db_column='id_patient', on_delete=django.db.models.deletion.DO_NOTHING, to='core.patient'),
        ),
        migrations.AlterField(
            model_name='fileimageskin',
            name='consultation',
            field=models.ForeignKey(db_column='id_consultation', on_delete=django.db.models.deletion.DO_NOTHING, to='core.consultation'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='cellphone',
            field=models.IntegerField(db_column='nb_cellphone', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='cpf',
            field=models.CharField(db_column='tx_national_id', max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(db_column='dt_date_of_birth'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(db_column='tx_email', max_length=254),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], db_column='tx_gender', max_length=10),
        ),
    ]
