# Generated by Django 5.2.1 on 2025-06-03 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_patient_user_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='user_created_by',
            field=models.ForeignKey(db_column='tx_user_created_by', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
