# Generated by Django 5.2.1 on 2025-06-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_patient_user_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='cellphone',
            field=models.IntegerField(db_column='nb_cellphone', max_length=11, null=True),
        ),
        migrations.AlterModelTable(
            name='consultation',
            table='consultation',
        ),
        migrations.AlterModelTable(
            name='patient',
            table='patient',
        ),
    ]
