# Generated by Django 5.2.1 on 2025-06-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_patient_cellphone_alter_consultation_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='cellphone',
            field=models.CharField(db_column='nb_cellphone', null=True),
        ),
    ]
