# Generated by Django 5.2.1 on 2025-06-03 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_patient_cellphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(db_column='id_patient', on_delete=django.db.models.deletion.CASCADE, to='core.patient'),
        ),
    ]
