# Generated by Django 5.2.1 on 2025-06-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_consultation_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='photo_location',
            field=models.CharField(db_column='tx_photo_location', max_length=255, null=True),
        ),
    ]
