# Generated by Django 5.2.1 on 2025-06-14 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_consultation_photo_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileimageskin',
            name='consultation',
            field=models.ForeignKey(db_column='id_consultation', on_delete=django.db.models.deletion.CASCADE, to='core.consultation'),
        ),
    ]
