# Generated by Django 5.2.1 on 2025-06-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_fileimageskin_consultation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='model_version',
            field=models.CharField(db_column='tx_model_version', default='v1', max_length=50),
        ),
    ]
