# Generated by Django 5.2.1 on 2025-06-15 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_analysisresult_model_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='image',
            field=models.ForeignKey(db_column='id_image', on_delete=django.db.models.deletion.CASCADE, to='core.fileimageskin'),
        ),
    ]
